jobs:
- template: azure-pipelines-template.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04

- template: azure-pipelines-template.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016

- job: Trigger Website build
  dependsOn:
  - Linux
  - Windows
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: ./tools/website.sh
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Trigger Website build
